"""LateLog DateTime error again

Revision ID: dcc15719e54e
Revises: cda5be67dec5
Create Date: 2024-12-10 17:11:31.558697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc15719e54e'
down_revision = 'cda5be67dec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_log', schema=None) as batch_op:
        batch_op.alter_column('transaction_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_log', schema=None) as batch_op:
        batch_op.alter_column('transaction_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
